### ISSUE TITLE
Markdown usage appears broken

### ISSUE THREAD

**Issue by axelav** [observablehq/prettier-react-tachyons#5]
When using this parser, I get a `Prettier: failed to parse buffer` error for markdown files. I'm just editing a README in a pretty standard app using `create-react-app` 

Here's my prettier config from `package.json`:

```json

  "prettier": {
    "parser": "./node_modules/@observablehq/prettier-react-tachyons",
    "autoformat": 0,
    "semi": false,
    "arrowParens": "avoid",
    "trailingComma": "none",
    "jsxBracketSameLine": false,
    "bracketSpacing": true,
    "singleQuote": true
  }
```

**Comment by tmcw** [comment]
You'll probably want to use the [overrides syntax](https://prettier.io/docs/en/configuration.html) in your prettierrc if you're formatting more than one language.

**Comment by axelav** [comment]
ah ha - I was looking for something like that in the docs but couldn't find it. that should do the trick. thanks for the prompt reply!
